baseURL = 'https://raleighstormwater.com'
description = 'Raleigh Stormwater inspections, maintenance and installations. Best Management Practices implemented and maintained to engineered plans.'
languageCode = 'en-us'
googleAnalytics="G-7V5YR3TCLX"
title = 'Raleigh Stormwater'
theme = 'ananke'
[params]
    author = "NC SCM Inspector"
    subtitle = 'Drainage Solutions for Stormwater in NC'
    [params.contact]
        email = 'help@raleighstormwater.com'

[[params.customCSS]]
 href = "/assets/ananke/css/customstyles.css"